version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
    build:
    commands:
      - echo Build started on `date`
      - ID= aws s3api list-buckets --query Owner.ID --output text
      - aws s3api put-bucket-acl --bucket ${S3_BUCKET} --acl bucket-owner-full-control --acl public-read   # to give acl to website bucket
      - echo NOTHING TO BUILD AS IT IS TEST PIPELINE
artifacts:
  files:
    - "**/*"                   # to get all files of  GITHUB repo in s3 bicket
